<a href="https://colab.research.google.com/github/JoySoon/Python_Study/blob/main/2023/%EC%88%98%EC%97%85%ED%95%84%EA%B8%B0/ch05_01_numpy_%EA%B8%B0%EC%B4%88_KSW.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy 기초

## 배열(Array)
* 많은 데이터를 하나의 변수에 넣는 법? : **리스트**
* 하지만 리스트는...
    * 속도가 느리다
    * 메모리를 많이 차지한다

> 그래서? **배열(Array)**을 사용한다

* 적은 메모리로 많은 데이터를 빠르게 처리할 수 있음

## 특징
1. 모든 원소가 같은 **자료형**이어야 함
2. 원소의 갯수를 바꿀 수 없음

> 그런데 파이썬은 자체적으로 배열 자료형을 제공하지 않음<br>
> 그래서 우리는 **넘파이(Numpy)** 패키지를 import해서 사용 

In [ ]:
#!pip install numpy (jupyter, colab에서는 필요X)
import numpy as np

## 1차원 배열
* 리스트나 튜플처럼 한 줄로 이루어진 형태의 배열

In [ ]:
np.array([1, 2, 3])

array([1, 2, 3])

In [ ]:
arr = np.array(range(10))
arr, type(arr)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), numpy.ndarray)

## ndarray
* 배열 객체 타입(자료형)
* 리스트와 동일해 보이지만 차이가 많음

|자료형|특징|
|:-|:-|
|리스트(list)|각각의 원소가 다른 자료형이 될 수 있음|
|배열(array)|연속적인 메모리 배치를 가지기 때문에 모든 원소가 같은 자료형이어야 함<br>원소에 대한 접근과 반복문 실행이 빨라짐|

In [ ]:
import random

def average_python(n):
    '''
    n개의 랜덤한 0 ~ 1의 실수를 평균해주는 함수
    '''
    s = 0
    for i in range(n):
        s += random.random()
    return s/n

In [ ]:
%time average_python(100_000)

CPU times: user 14.3 ms, sys: 0 ns, total: 14.3 ms
Wall time: 18.8 ms


0.49865794290299537

In [ ]:
%timeit average_python(100_000)

9.92 ms ± 174 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [ ]:
def average_numpy(n):
    'n개의 랜덤한 0~1의 실수를 numpy를 사용해서 평균내는 함수'
    s = np.random.random(n)
    return s.mean()

In [ ]:
%time average_numpy(100_000)

CPU times: user 3.3 ms, sys: 0 ns, total: 3.3 ms
Wall time: 3.32 ms


0.5010029902867872

In [ ]:
%timeit average_numpy(100_000) # numpy = c, c++에서 처리

843 µs ± 184 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


## 벡터화 연산
* 배열 객체는 **배열의 각 원소에 대한 반복 연산을 하나의 명령어로 처리**하는 벡터화 연산(vectorized operation)을 지원

In [ ]:
data = list(range(10))
data

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
# 리스트 객체에 정수를 곱하면 객체의 크기가 해당 정수 배만큼 증가
data * 2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
# 여러 개의 데이터를 모두 2배 할 때 (파이썬)
%%time
answer = []
for v in data:
    answer.append(v * 2)
answer 

CPU times: user 18 µs, sys: 1 µs, total: 19 µs
Wall time: 22.4 µs


[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [ ]:
%%timeit
answer = []
for v in data:
    answer.append(v * 2)
answer 

839 ns ± 48.3 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [ ]:
# 리스트 컴프리헨션
%%time
[ v * 2 for v in data]

CPU times: user 4 µs, sys: 0 ns, total: 4 µs
Wall time: 6.44 µs


[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [ ]:
%%timeit
[ v * 2 for v in data]

666 ns ± 8.46 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [ ]:
# 벡터화 연산 행렬처럼 취급
arr = np.array(data)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
%time arr * 2

CPU times: user 77 µs, sys: 3 µs, total: 80 µs
Wall time: 82.5 µs


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
%timeit arr * 2

1.45 µs ± 67.2 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


* 벡터화 연산은 비교 연산과 논리 연산을 포함한 모든 종류의 수학 연산에 대해 적용

In [ ]:
a = np.array(range(1, 4))
b = np.array(range(10, 40, 10))
a, b

(array([1, 2, 3]), array([10, 20, 30]))

In [ ]:
a * 2 + b # 산술 연산

array([12, 24, 36])

In [ ]:
a == 2, b > 10 # 비교 연산

(array([False,  True, False]), array([False,  True,  True]))

In [ ]:
(a == 2) & (b > 10), (a == 2) | (b > 10) # 논리 연산 

(array([False,  True, False]), array([False,  True,  True]))

코딩테스트에는 외부프로그램 지원 X ex) numpy..
리스트 컴프리헨션은 계속 해주어야 함


## 2차원 배열
* `ndarray`는 N-dimensional Array의 약자, 즉 1차원 배열 이외에도 2차원 배열, 3차원 배열 등의 다차원 배열 자료 구조를 지원
* 2차원 배열 = 행렬 (matrix)
* 가로줄 : 행(row), 세로줄 : 열(column)
> 엑셀 스프레드시트와 같은 형태의 배열

* 리스트의 리스트(list of list)를 이용하여 2차원 배열 생성
    * 안쪽 리스트의 길이 : 행렬의 열의 수 (가로 크기)
    * 바깥쪽 리스트의 길이 : 행렬의 행의 수 (세로 크기)

In [ ]:
arr = np.array([[0, 1, 2],[3, 4, 5]])
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
# 행의 갯수, 열의 갯수
len(arr), len(arr[0])

(2, 3)

## 💡 연습문제 1
> 아래 모양의 행렬 만들어 보기
```
10 20 30 40
50 60 70 80
```

In [ ]:
np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80]
])

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [ ]:
np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
]) * 10

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [ ]:
np.arange(10, 90, 10).reshape(2, -1)
(np.arange(1, 9) * 10).reshape(2, -1)

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

## 3차원 배열

In [ ]:
# 크기를 나타낼 때는 가장 바깥쪽 리스트의 길이부터 가장 안쪽 리스트 길이의 순서로 표시
# m : matrix
# t : three-dimention
t = np.array(
    [
        [
            [1, 2, 3, 4],
            [5, 6 ,7 ,8],
            [9, 10, 11, 12]
        ],
        [
            [11, 12, 13, 14],
            [15, 16, 17, 18],
            [19, 20, 21, 22]
        ],
    ]
) # 2 X 3 X 4
t

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

In [ ]:
# 깊이, 행, 열
len(t), len(t[0]), len(t[0][0])

(2, 3, 4)

## 배열의 차원과 크기 알아내기
* `ndim`, `shape` **속성** 사용
> 속성 : 괄호 없이 이름만 써서 값을 호출

* `ndim` : 배열의 차원
* `shape` : 배열의 크기

In [ ]:
a = np.array(range(1, 4))
a

array([1, 2, 3])

In [ ]:
a.ndim, a.shape # 속성 property 1차원 길이가 3

(1, (3,))

In [ ]:
m = np.array((range(3), range(3, 6)))
m

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
m.ndim, m.shape 

(2, (2, 3))

In [ ]:
t.ndim, t.shape

(3, (2, 3, 4))

## 배열의 복사
* copy와 view의 차이점은 copy는 새 배열(깊은 복사)이고 view는 원래 배열과 연결 되어 있다는 것(얕은 복사)
* copy는 데이터를 소유하며 copy에 대한 변경 사항은 원본 배열에 영향을 미치지 않으며 원본 배열에 대한 변경은 copy에 영향을 주지 않음
* view는 데이터를 소유하지 않으며 view에 대한 모든 변경 사항은 원래 배열에 영향을 미치고 원래 배열에 대한 모든 변경 사항은 보기에 영향을 줌

In [ ]:
import numpy as np

arr = np.array(range(1, 6))
x = arr.copy()
arr[0] = 40
print(f"arr : {arr}")
print(f"x: {x}")

arr : [40  2  3  4  5]
x: [1 2 3 4 5]


In [ ]:
arr = np.array(range(1, 6))
x = arr.view()
arr[0] = 40
print(f"arr : {arr}")
print(f"x: {x}")

arr : [40  2  3  4  5]
x: [40  2  3  4  5]


In [ ]:
arr = np.array(range(1, 6))
x = arr
arr[0] = 40
print(f"arr : {arr}")
print(f"x: {x}")

arr : [40  2  3  4  5]
x: [40  2  3  4  5]


In [ ]:
arr = np.array(range(1, 6))
x = arr.view(float)
arr[0] = 40
print(f"arr : {arr}")
print(f"x: {x}")

arr : [40  2  3  4  5]
x: [2.0e-322 9.9e-324 1.5e-323 2.0e-323 2.5e-323]


In [ ]:
import numpy as np

arr = np.array(range(1, 6))

x = arr.copy()
y = arr.view()

# 배열 데이터 소유 여부 반환
print(x.base)
print(y.base)

None
[1 2 3 4 5]


## 배열의 인덱싱

### 일차원 배열
* 리스트의 인덱싱과 같음

In [ ]:
a = np.array(range(5))
print(a)
a[2], a[-1]

[0 1 2 3 4]


(2, 4)

### 다차원 배열
* 콤마(comma, `,`)를 사용하여 접근
* 콤마로 구분된 차원을 축(axis)라고 함
    * like 그래프의 x축, y축

In [ ]:
b = np.array([[0, 1, 2], [3, 4, 5]])
print(b, b.ndim, b.shape)

[[0 1 2]
 [3 4 5]] 2 (2, 3)


In [ ]:
# b[0][0]
b[0, 0] # 첫번째 행의 첫번째 열

0

In [ ]:
b[0, 1] # 첫번째 행의 첫번째 열

1

In [ ]:
b[-1, -1] # 마지막 행의 마지막 열

5

## 배열 슬라이싱
* 다차원 배열의 원소 중 2개 이상의 복수 개를 접근하려면 일반적인 파이썬 슬라이싱(slicing)과 comma(,)를 함께 사용

In [ ]:
a = np.array((range(4), range(4,8)))
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
# a[0]
a[0, :] # 첫번째 행의 전체 열

array([0, 1, 2, 3])

In [ ]:
a[:, 1] # 두번재 열 전체 (모든 행의 두번째 열)

array([1, 5])

In [ ]:
a[1, 1:] # 두번째 행의 두번째 열부터 끝열까지

array([5, 6, 7])

In [ ]:
a[:2, :2] # 첫번째 행에서 두번재 행까지, 첫번째 열에서 두번째 열까지

array([[0, 1],
       [4, 5]])

In [ ]:
a[:, 2:]

array([[2, 3],
       [6, 7]])

## 💡 연습문제 2

In [ ]:
m = np.array([[0,  1,  2,  3,  4],
              [5,  6,  7,  8,  9],
              [10, 11, 12, 13, 14]])
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
#@markdown (1) 값 7을 인덱싱
m[1, 2], m[1, -3], m[-2, 2], m[-2, -3]

(7, 7, 7, 7)

In [ ]:
#@markdown (2) 값 14을 인덱싱
m[2, 4], m[2, -1], m[-1, 4], m[-1, -1]

(14, 14, 14, 14)

In [ ]:
#@markdown (3) 배열 [6,7]을 슬라이싱
m[1, 1:3], m[-2, 1:3], m[1, -4:-2], m[-2, -4:-2]

(array([6, 7]), array([6, 7]), array([6, 7]), array([6, 7]))

In [ ]:
#@markdown (4) 배열 [7,12]을 슬라이싱
m[1:,2], m[-2:, 2], m[1:, -3], m[-2:, -3]

(array([ 7, 12]), array([ 7, 12]), array([ 7, 12]), array([ 7, 12]))

In [ ]:
#@markdown (5) 배열 [[3,4],[8,9]]을 슬라이싱
print(m[:2,3:])
print(m[:-1,3:])
print(m[:2,-2:])
print(m[:-1,-2:])

[[3 4]
 [8 9]]
[[3 4]
 [8 9]]
[[3 4]
 [8 9]]
[[3 4]
 [8 9]]


## 배열 인덱싱
* 대괄호(Bracket, [])안의 인덱스 정보로 숫자나 슬라이스가 아니라 위치 정보를 나타내는 또다른 `ndarray` 배열을 받을 수 있음 (인덱스 배열)
* 일종의 조건 검색 기능

### 불리언 (Boolean) 배열 인덱싱
* 인덱스 배열의 원소가 True, False 두 값으로만 구성되며 인덱스 배열의 크기가 원래 ndarray 객체의 크기와 같아야 함

In [ ]:
# 0 ~ 8 사이의 (끝포함) 짝수만 가진 배열
a1 = np.array(range(0, 9, 2))
a2 = np.array([i for i in range(9) if not (i % 2)])
a1, a2 

(array([0, 2, 4, 6, 8]), array([0, 2, 4, 6, 8]))

In [ ]:
# 짝수인 원소만 골라내고 싶다면?
# 짝수에 대응하는 곳에 True, 홀수에 대응하는 곳에 False
a = np.array(range(10))
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
idx = np.array([True, False, True, False, True, False, True, False, True, False])
idx

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [ ]:
a[idx]

array([0, 2, 4, 6, 8])

In [ ]:
# 조건문 연산
a % 2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

In [ ]:
a % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [ ]:
a[a % 2 == 0], a[a % 2 != 0], a[a % 3 == 0], a[a % 3 == 1]

(array([0, 2, 4, 6, 8]),
 array([1, 3, 5, 7, 9]),
 array([0, 3, 6, 9]),
 array([1, 4, 7]))

### 정수 배열 인덱싱
* 인덱스 배열의 원소 각각이 원래 `ndarray` 객체 원소 하나를 가리키는 인덱스 정수이여야 함

In [ ]:
a = np.array(range(1, 10)) * 11
a

array([11, 22, 33, 44, 55, 66, 77, 88, 99])

In [ ]:
idx = np.array([0, 2, 4, 6, 8])
a[idx]

array([11, 33, 55, 77, 99])

* 이 때는 배열 인덱스의 크기가 원래의 배열 크기와 달라도 상관없음
* 같은 원소를 반복해서 가리키는 경우에는 배열 인덱스가 원래의 배열보다 더 커지기도 함

In [ ]:
idx = np.array([0] * 6 + [1] * 5 + [2] * 5)
a[idx]

array([11, 11, 11, 11, 11, 11, 22, 22, 22, 22, 22, 33, 33, 33, 33, 33])

### 다차원 배열에서의 배열 인덱싱

In [ ]:
a = np.array([range(1,5), range(5,9), range(9,13)])
a, a.ndim, a.shape

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]), 2, (3, 4))

In [ ]:
print(a[:,[0,3]])
print(a[:,[0,-1]])
print(a[:,[True, False, False,True]])

[[ 1  4]
 [ 5  8]
 [ 9 12]]
[[ 1  4]
 [ 5  8]
 [ 9 12]]
[[ 1  4]
 [ 5  8]
 [ 9 12]]


In [ ]:
a[[2, 0, 1],:]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

## 💡 연습문제 3

In [ ]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
# (1) 3의 배수 찾기
x[x % 3 == 0], x[x % 3 != 0]
# x = np.array(range(0, 20, 3))

(array([ 3,  6,  9, 12, 15, 18]),
 array([ 1,  2,  4,  5,  7,  8, 10, 11, 13, 14, 16, 17, 19, 20]))

In [ ]:
# (2) 4로 나누면 1이 남는 수 찾기
x[x % 4 == 1], x[x // 4 == 1]

(array([ 1,  5,  9, 13, 17]), array([4, 5, 6, 7]))

In [ ]:
# (3) 3로 나누면 나누어지고 4로 나누면 1이 남는 수 찾기
x[(x % 3 == 0) & (x % 4 == 1)], x[(x % 3 == 0) | (x % 4 == 1)]

(array([9]), array([ 1,  3,  5,  6,  9, 12, 13, 15, 17, 18]))

## 배열 검색

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
arr

array([1, 2, 3, 4, 5, 4, 4])

In [ ]:
# np.where(배열 비교/논리 연산) - > 조건을 만족킨 값의 인덱스 반환
z = np.where(arr == 4)
z

(array([3, 5, 6]),)

In [ ]:
arr = np.array(range(1, 9))
z = np.where(arr % 2 == 0) # 짝수

z, arr[z], arr[arr % 2 == 0]

((array([1, 3, 5, 7]),), array([2, 4, 6, 8]), array([2, 4, 6, 8]))