<a href="https://colab.research.google.com/github/JoySoon/Python_Study/blob/main/2023/%EC%88%98%EC%97%85%ED%95%84%EA%B8%B0/%EB%B3%B5%EC%8A%B5/ch05_02%2B03%2B04_%EB%B3%B5%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr1 = np.arange(1, 4) # 1, 2, 3
arr2 = np.arange(4, 7) # 4, 5, 6
np.concatenate([arr1, arr2])

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.concatenate([arr1, arr2, arr1, arr2])

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6])

In [ ]:
arr1 = arr1.reshape(3, 1)
arr2 = arr2.reshape(3, 1)

np.concatenate([arr1, arr2])
np.concatenate([arr1, arr2], axis=0)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [ ]:
np.concatenate([arr1, arr2], axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
a1 = np.ones((2, 3))
a2 = np.zeros((2, 2))
np.hstack((a1, a2))

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [ ]:
# b1 = np.ones((2, 3))
b1 = np.ones_like(a1)
b2 = np.zeros((3, 3))
np.vstack((b1, b2))

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
c1 = np.ones((3, 4))
c2 = np.zeros_like(c1)
np.dstack((c1, c2)) # 행, 열 길이 같고, 가장 마지막(안쪽의) 차원이 1증가하면서 합쳐진다

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [ ]:
# c = np.stack([c1, c2])
c = np.stack([c1, c2], axis=0) # 행기준
c

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
np.stack([c1, c2], axis=-1) # 차원을 추가하면서 합쳐지는 (dstack)
np.stack([c1, c2], axis=2)

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [ ]:
np.stack([c1, c2], axis=1) # 열 기준

array([[[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]]])

In [ ]:
# r_ -> hstack. 1,2,3 / 4,5,6
np.r_[np.arange(1,4), np.arange(4,7)]

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.r_[np.arange(1,4), np.arange(4,7), np.arange(4,7)]

array([1, 2, 3, 4, 5, 6, 4, 5, 6])

In [ ]:
np.c_[np.arange(1,4), np.arange(4,7)]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
np.arange(1,4)[:, np.newaxis], np.arange(4,7)[:, np.newaxis]

(array([[1],
        [2],
        [3]]), array([[4],
        [5],
        [6]]))

In [ ]:
np.concatenate((np.arange(1,4)[:, np.newaxis], np.arange(4,7)[:, np.newaxis]), axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
# a = np.arange(6).reshape(2, -1)
a = np.arange(6).reshape(3, -1)
print(np.tile(a, 3)) # 모양을 지키면서 반복
print(np.repeat(a, 3)) # flattern 시킨 다음에, 각 원소들을 그 위치에 반복

[[0 1 0 1 0 1]
 [2 3 2 3 2 3]
 [4 5 4 5 4 5]]
[0 0 0 1 1 1 2 2 2 3 3 3 4 4 4 5 5 5]


In [ ]:
arr = np.arange(7) # 0, 1, 2, 3, 4, 5, 6
arr

array([0, 1, 2, 3, 4, 5, 6])

In [ ]:
np.array_split(arr, 3)

[array([0, 1, 2]), array([3, 4]), array([5, 6])]

In [ ]:
arr = np.arange(6)
np.split(arr, 3) # array_split -> 되는대로 3등분, split: 엄격하게 약수로 맞게 입력해야 쪼개줌

[array([0, 1]), array([2, 3]), array([4, 5])]

In [ ]:
arr = np.arange(1, 19).reshape(-1, 3)
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [ ]:
# np.array_split(arr, 3) # 행 방향으로 짜름
np.array_split(arr, 3, axis=0) # 행 방향으로 짜름

[array([[1, 2, 3],
        [4, 5, 6]]), array([[ 7,  8,  9],
        [10, 11, 12]]), array([[13, 14, 15],
        [16, 17, 18]])]

In [ ]:
np.array_split(arr, 3, axis=1) # 행 방향으로 짜름

[array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]), array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]]), array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]])]

In [ ]:
# 브로드캐스팅 : 크기가 작은 배열을 자동으로 반복확장하여 크기가 큰 배열에 맞추는 방법
x = np.arange(5)
x + 1

array([1, 2, 3, 4, 5])

In [ ]:
x + np.ones_like(x) * 1

array([1, 2, 3, 4, 5])

In [ ]:
x + 10

array([10, 11, 12, 13, 14])

In [ ]:
np.ones_like(x) * 10

array([10, 10, 10, 10, 10])

In [ ]:
# x + np.ones_like(x) * 10
x + np.full_like(x, 10)

array([10, 11, 12, 13, 14])

In [ ]:
x = np.vstack([range(7)[i:i+3] for i in range(5)]) 
x

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [ ]:
y = np.arange(5).reshape(-1, 1)
y

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [ ]:
x + y

array([[ 0,  1,  2],
       [ 2,  3,  4],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 8,  9, 10]])

In [ ]:
x = np.arange(1, 5) # 1, 2, 3, 4

In [ ]:
np.sum(x), x.sum()

(10, 10)

In [ ]:
x.min(), x.max()

(1, 4)

In [ ]:
x.argmin(), x.argmax()

(0, 3)

In [ ]:
x.mean()

2.5

In [ ]:
np.median(x)

2.5

In [ ]:
np.any(x > 4), np.any(x > 2)

(False, True)

In [ ]:
np.all(x > 4), np.all(x > 2), np.all(x >= 0)

(False, False, True)

In [ ]:
x = np.array(((1, 1), (2, 2)))
x

array([[1, 1],
       [2, 2]])

In [ ]:
x.sum()

6

In [ ]:
x.sum(axis=0) # 행 내부에 있는 열들간의 연산, 행의 대푯값 (axis=0)

array([3, 3])

In [ ]:
x.sum(axis=1) # 열 내부에 있는 행들간의 연산, 열의 대푯값 (axis=1)

array([2, 4])

In [ ]:
a = np.random.randint(1, 20, 12).reshape(3, -1)
a

array([[ 8, 19,  5,  8],
       [15, 17,  7,  4],
       [ 3,  3,  5, 12]])

In [ ]:
np.sort(a) # 행을 그대로, 열들 간의 정리. axis=0
np.sort(a, axis=1) # 행을 그대로, 열들 간의 정리. axis=1
np.sort(a, axis=-1) # 행을 그대로, 열들 간의 정리. axis=-1

array([[ 5,  8,  8, 19],
       [ 4,  7, 15, 17],
       [ 3,  3,  5, 12]])

In [ ]:
np.sort(a, axis=0) # 열을 그대로, 행들 간의 정리. axis=0

array([[ 3,  3,  5,  4],
       [ 8, 17,  5,  8],
       [15, 19,  7, 12]])

In [ ]:
a.sort(axis=1) # in-place

In [ ]:
a

array([[ 5,  8,  8, 19],
       [ 4,  7, 15, 17],
       [ 3,  3,  5, 12]])

In [ ]:
np.argsort(a)

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [ ]:
np.argsort(a, axis=0)

array([[2, 2, 2, 2],
       [1, 1, 0, 1],
       [0, 0, 1, 0]])

In [ ]:
x = np.random.randint(0, 100, 12).reshape(3, -1)
x

array([[89, 13, 76, 37],
       [81, 84, 42, 91],
       [59, 35, 10, 79]])

In [ ]:
x[:, np.argsort(x[1])]

array([[76, 89, 13, 37],
       [42, 81, 84, 91],
       [10, 59, 35, 79]])

In [ ]:
x = np.random.randint(-30,30,30)
x

array([  2,  29,  25,  -5,  16, -18,  23,  21,  -6,  16, -22, -15,   5,
        22, -12,   7,   8, -10,   3,   3,  -9,  10, -13,  24,  26,  -3,
       -15,  22, -10,  24])

In [ ]:
len(x)

30

In [ ]:
np.mean(x), x.mean()

(4.933333333333334, 4.933333333333334)

In [ ]:
np.var(x), x.var()

(239.86222222222221, 239.86222222222221)

In [ ]:
np.std(x), x.std()

(15.487485987797445, 15.487485987797445)

In [ ]:
np.max(x), np.min(x)

(29, -22)

In [ ]:
np.median(x) # 짝수개일 경우, 두 값의 평균을 쓴다

4.0

In [ ]:
np.quantile(x, 0), np.percentile(x, 0) # 최솟값

(-22, -22.0)

In [ ]:
# 사분위수 => 1을 최대로 봤을 때의 비율수. 1/4, 2/4, 3/4...
# 백분위수는 100을 최대로 봤을 때의 값을 입력
np.quantile(x, 1/4), np.percentile(x, 25) # 1사분위수, 25백분위수

(-9.75, -9.75)

In [ ]:
np.quantile(x, 2/4), np.percentile(x, 50) # 2사분위수, 50백분위수, 중앙값

(4.0, 4.0)

In [ ]:
np.quantile(x, 3/4), np.percentile(x, 75) # 3사분위수, 75백분위수

(21.75, 21.75)

In [ ]:
np.quantile(x, 4/4), np.percentile(x, 100) # 최댓값

(29.0, 29.0)

In [ ]:
# np.random.seed(0) # 이후 나오는 랜덤값들이 순서가 일치
np.random.seed(10) # 이후 나오는 랜덤값들이 순서가 일치

In [ ]:
np.random.rand(5)

array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701])

In [ ]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.random.shuffle(x)

In [ ]:
x

array([5, 3, 4, 7, 6, 8, 9, 2, 1, 0])

In [ ]:
np.random.choice(x, 5, replace=False) # x 배열 안의 있는 값 중에 5개를 추출(비복원)

array([3, 9, 4, 8, 2])

In [ ]:
np.random.choice(5, 5, replace=False)

array([4, 2, 3, 0, 1])

In [ ]:
np.random.choice(np.arange(1, 46), 6, replace=False)

array([21, 17, 44, 34, 38, 20])

In [ ]:
np.random.choice(np.arange(1,7), 6)
np.random.choice(np.arange(1,7), 6, replace=True)

array([2, 5, 1, 1, 6, 2])

In [ ]:
np.random.choice(np.arange(1,7), 6, p=[0, 0, 0, 0.6, 0.2, 0.2])

array([6, 4, 5, 4, 4, 5])

In [ ]:
np.random.randn(10) # 0 평균, 표준편차 -1. -2.+2 => 99.9% 0에 가까울 수록 값들이 더 많이 등장

array([-0.9978168 ,  0.66989397,  0.64851164,  0.02573462,  0.58660498,
        0.28408516, -1.33168955,  1.27310627,  0.40924504, -0.60747309])

In [ ]:
np.random.randn(3, 5)

array([[ 0.93400955, -1.84373609,  0.47805208,  0.48526092, -0.47499732],
       [-1.16586593, -0.75562989,  0.5881038 , -1.43924512, -0.46122134],
       [ 1.21267456,  0.70466113, -0.45961232,  0.53482087,  1.46925737]])

In [ ]:
np.random.randint(10) # 최소 0, 최대 low

1

In [ ]:
np.random.randint(10, size=100) # 최소 0, 최대 low, size=100

array([7, 1, 7, 1, 8, 0, 6, 7, 5, 1, 2, 6, 1, 5, 8, 0, 3, 9, 6, 3, 0, 2,
       8, 9, 8, 0, 7, 7, 4, 6, 3, 4, 5, 3, 5, 9, 2, 3, 2, 2, 5, 8, 4, 1,
       6, 7, 1, 7, 1, 2, 9, 2, 7, 4, 6, 7, 3, 2, 3, 9, 2, 5, 0, 7, 2, 6,
       5, 7, 3, 7, 0, 3, 6, 0, 7, 2, 9, 5, 1, 0, 2, 3, 1, 4, 2, 0, 2, 8,
       8, 8, 6, 5, 8, 8, 8, 0, 6, 1, 2, 8])

In [ ]:
np.random.randint(1, 10) # 최소 low, 최대 high

8

In [ ]:
np.random.randint(1, 10, 100) # 최소 low, 최대 high, size

array([2, 2, 6, 6, 1, 9, 4, 8, 2, 6, 3, 4, 5, 6, 8, 7, 9, 1, 5, 7, 4, 6,
       4, 9, 4, 1, 7, 3, 4, 2, 5, 1, 6, 1, 9, 2, 4, 7, 1, 1, 7, 6, 8, 5,
       1, 1, 3, 3, 2, 7, 7, 8, 4, 1, 8, 8, 1, 3, 3, 1, 6, 9, 1, 6, 4, 7,
       8, 9, 1, 7, 1, 2, 1, 2, 5, 1, 2, 8, 4, 1, 9, 2, 6, 5, 6, 5, 4, 5,
       5, 2, 2, 3, 2, 2, 3, 3, 3, 6, 9, 2])

In [ ]:
# 가격이 1만원 주식
price = 10000
# 일간 수익률 -> 기댓값(평균) 0, 표준편차 1%=0.01 (표준정규분포)
days = 250
daily_earning_rate = np.random.randn(days) / 100
print(daily_earning_rate)
# 250일 동안의 주가를 무작위로 생성
# 주가 -> 전일 가격 * (1 + 당일 수익률)
price_arr = np.empty(days)
for i, v in enumerate(daily_earning_rate):
    print(v)
    price *= (1 + v)
    print(price)
    price_arr[i] = price
    print(price_arr[i])
    print(price_arr)
price_arr

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
  9.36396397e+003  9.48018128e+003  9.47094633e+003  9.61249318e+003
  9.60532037e+003  9.71035711e+003  9.68020747e+003  9.66617363e+003
  9.80550920e+003  9.68061985e+003  9.70387342e+003  9.64841673e+003
  9.67643788e+003  9.68823757e+003  9.91276800e+003  9.94772170e+003
  9.82704587e+003  9.78721318e+003  9.85736678e+003  9.82691793e+003
  9.89743376e+003  1.00333625e+004  1.01311798e+004  1.00191360e+004
  9.96190767e+003  9.97056191e+003  9.79310616e+003  9.86318919e+003
  9.83725414e+003  9.82012583e+003  9.85487836e+003  9.79700432e+003
  9.94513050e+003  1.00202074e+004  9.88864650e+003  9.89406324e+003
  9.84114910e+003  9.92050724e+003  9.99486622e+003  1.01327292e+004
  1.00849438e+004  1.00571793e+004  1.00811975e+004  1.01165346e+004
  1.00511154e+004  1.01229646e+004  1.01155619e+004  9.86649423e+003
  9.62859020e+003  9.53269455e+003  9.67834366e+003  9.76661108e+003
  9.79936165e+003  9.75961283e+003  9.74879114e+003  9.80340001e+00

array([10021.14478591,  9887.59045816,  9867.06679406,  9866.29428013,
        9902.3325224 ,  9862.72042135,  9974.41824385,  9964.58184237,
        9943.55436322,  9786.42256596,  9695.44169656,  9637.47230073,
        9499.37014997,  9455.01202713,  9370.4705316 ,  9059.58933072,
        9140.69798435,  9250.3524845 ,  9285.65225525,  9294.02539383,
        9290.54490961,  9073.78032848,  9067.70547028,  8935.94181668,
        8849.13101204,  8725.45659389,  8732.95107065,  8964.43452099,
        8920.96420621,  9043.19026776,  9084.30975926,  9227.71042863,
        9338.09046174,  9166.34667583,  9268.03641328,  9318.84170481,
        9211.51469493,  9249.25568887,  9117.17747281,  9135.03741463,
        9240.83964847,  9262.95786905,  9151.14124925,  9123.91384062,
        9155.67833109,  9230.59804117,  9249.10545453,  9215.29631442,
        9164.22845786,  9208.37298983,  9358.88409262,  9424.58920078,
        9363.96397068,  9480.18128493,  9470.94632576,  9612.49318063,
      

In [ ]:
x = np.random.randint(1, 10, 100)
x

array([1, 2, 9, 5, 3, 3, 4, 9, 4, 2, 8, 4, 7, 2, 1, 3, 1, 8, 1, 1, 2, 7,
       5, 6, 1, 8, 7, 3, 3, 5, 2, 6, 1, 7, 9, 8, 5, 2, 6, 4, 4, 2, 9, 2,
       6, 6, 1, 2, 8, 8, 9, 5, 3, 6, 6, 5, 3, 5, 7, 4, 7, 2, 9, 7, 2, 6,
       1, 3, 2, 4, 9, 5, 7, 2, 3, 4, 4, 8, 8, 2, 6, 6, 6, 3, 4, 1, 1, 6,
       9, 7, 7, 5, 6, 5, 5, 3, 9, 7, 8, 9])

In [ ]:
np.unique(x)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.unique(x, return_counts=True)

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([11, 14, 11, 10, 11, 13, 11,  9, 10]))

In [ ]:
key, value = np.unique(x, return_counts=True)
print(key)
print(value)

[1 2 3 4 5 6 7 8 9]
[11 14 11 10 11 13 11  9 10]


In [ ]:
# 2개의 시퀀스를, 인덱스로 묶어줌 zip
list(zip(key, value))

[(1, 11),
 (2, 14),
 (3, 11),
 (4, 10),
 (5, 11),
 (6, 13),
 (7, 11),
 (8, 9),
 (9, 10)]

In [ ]:
dict(list(zip(key, value)))

{1: 11, 2: 14, 3: 11, 4: 10, 5: 11, 6: 13, 7: 11, 8: 9, 9: 10}

In [ ]:
dict(zip(key, value))

{1: 11, 2: 14, 3: 11, 4: 10, 5: 11, 6: 13, 7: 11, 8: 9, 9: 10}

In [ ]:
dict(zip(*np.unique(x, return_counts=True)))

{1: 11, 2: 14, 3: 11, 4: 10, 5: 11, 6: 13, 7: 11, 8: 9, 9: 10}

In [ ]:
x = np.random.randint(30, size=10)
x

array([ 3,  3, 10, 19, 16,  1, 20, 29, 11, 11])

In [ ]:
dict(zip(*np.unique(x, return_counts=True)))

{1: 1, 3: 2, 10: 1, 11: 2, 16: 1, 19: 1, 20: 1, 29: 1}

In [ ]:
np.bincount(x, minlength=30)

array([0, 1, 0, 2, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1])

In [ ]:
np.arange(30), np.bincount(x, minlength=30)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]),
 array([0, 1, 0, 2, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 1]))

In [ ]:
dict(zip(np.arange(30), np.bincount(x, minlength=30)))

{0: 0,
 1: 1,
 2: 0,
 3: 2,
 4: 0,
 5: 0,
 6: 0,
 7: 0,
 8: 0,
 9: 0,
 10: 1,
 11: 2,
 12: 0,
 13: 0,
 14: 0,
 15: 0,
 16: 1,
 17: 0,
 18: 0,
 19: 1,
 20: 1,
 21: 0,
 22: 0,
 23: 0,
 24: 0,
 25: 0,
 26: 0,
 27: 0,
 28: 0,
 29: 1}

In [ ]:
eval("1 + 1")

2

In [ ]:
eval("len([1, 2, 3])")

3

In [ ]:
eval("np.random.randint(5, 10, 10)")

array([5, 8, 5, 9, 6, 8, 8, 9, 7, 6])